# Generated by Django 5.0.7 on 2024-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Communicationdetails_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Communicationdetails_landline',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Landline Number'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Communicationdetails_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Communicationdetails_web',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Legalinfo_aadhar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Aadhar Number'),
        ),
        migrations.AlterField(
            model_name='form',
            name='Legalinfo_pancard',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='PAN Card Number'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Approved by AO', 'Approved by AO'), ('Approved by CEO', 'Approved by CEO'), ('Approved by Membership Committee', 'Approved by Membership Committee'), ('Approved by OB', 'Approved by OB'), ('waiting for payment', 'Waiting for Payment'), ('payment done (approved as Member)', 'Payment Done (Approved as Member)'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True, verbose_name='Form Status'),
        ),
    ]
